#!/usr/bin/env bash
rm -rf dist/*.spec*
cp package.json dist
cp package-lock.json dist
cp README.md dist
cp LICENSE dist
cp src/*.cjs dist
./append-shebang.cjs
buildhash=$(git rev-parse --short HEAD)
./modify-buildhash.cjs $buildhash